// Narrated action contracts (Checkpoint 1): every semantic action is declared as DATA. It lists entities,
// preconditions, start state, bridge, trajectory, events, contact rules, end state, affected entities, the state
// handed on, measurable validation, future engine commands and framing requirements. world.ts executes these
// contracts deterministically; nothing here calls the rendering engine.

export const CONTRACT_SET_VERSION = '1.0.0';
export const CONTRACT_IDS = [
  'look_at', 'jump', 'celebrate', 'remain_still', 'warning', 'move_to', 'press_button', 'spawn_coin', 'grow_coin',
  'move_safely', 'confident_pose', 'tip_coin_onto', 'fall_prone', 'reset_button', 'off_screen_teacher_cue',
] as const;
export type ContractId = (typeof CONTRACT_IDS)[number];
export type Trajectory = 'in_place' | 'yaw_turn' | 'path' | 'vertical_arc' | 'ballistic' | 'scale_about_base' | 'pivot_bottom_front_edge' | 'coupled_fall' | 'state_only' | 'none';

export interface ActionContract {
  id: ContractId; version: string;
  entities: string[];                 // roles: agent, patient, prop:button, prop:coin, mark, offscreen
  preconditions: string[];            // predicate ids evaluated by world.ts (see PRECONDITIONS)
  start: string;                      // required starting state
  bridge: 'turn_toward' | 'move_to' | null;
  trajectory: Trajectory;
  durationSec: [number, number];
  events: string[];
  contact: { between: [string, string]; rule: string; once: boolean } | null;
  end: string;
  affects: string[];
  handoff: string[];                  // state carried into later beats and shots
  validation: string[];               // measurable checks (world.ts summary / tests)
  engine: Array<{ action?: string; propEvent?: string; note?: string }>; // future engine commands (data only)
  framing: string[];                  // camera metadata for Checkpoint 2+ (not used here)
}

const c = (x: Omit<ActionContract, 'version'>): ActionContract => ({ ...x, version: CONTRACT_SET_VERSION });
export const CONTRACTS: Readonly<Record<ContractId, ActionContract>> = {
  look_at: c({ id: 'look_at', entities: ['agent', 'target'], preconditions: ['agent_exists', 'posture_allows_look'], start: 'any posture (prone: head-only look)', bridge: null, trajectory: 'state_only', durationSec: [0.6, 1.4], events: [], contact: null, end: 'lookTarget = target', affects: ['agent'], handoff: ['lookTarget', 'expression'], validation: ['target_resolvable'], engine: [{ action: 'look_at' }, { action: 'curious_lean', note: 'when curious' }], framing: ['face', 'target_in_or_implied'] }),
  jump: c({ id: 'jump', entities: ['agent'], preconditions: ['agent_standing'], start: 'standing, grounded', bridge: null, trajectory: 'vertical_arc', durationSec: [0.8, 1.0], events: ['takeoff', 'landing'], contact: null, end: 'standing at the take-off point', affects: ['agent'], handoff: ['pos', 'posture'], validation: ['vertical_displacement>=0.25m', 'landing_drift<=0.05m'], engine: [{ action: 'jump' }], framing: ['full_body', 'feet'] }),
  celebrate: c({ id: 'celebrate', entities: ['agent'], preconditions: ['agent_standing'], start: 'standing', bridge: null, trajectory: 'in_place', durationSec: [1.0, 1.6], events: [], contact: null, end: 'standing, same place', affects: ['agent'], handoff: ['expression'], validation: ['no_displacement'], engine: [{ action: 'victory_pose' }], framing: ['waist_up'] }),
  remain_still: c({ id: 'remain_still', entities: ['agent', 'mark?'], preconditions: ['agent_standing_or_seated', 'at_required_mark'], start: 'at the mark named by the narration (bridge if not)', bridge: 'move_to', trajectory: 'in_place', durationSec: [0.5, 30], events: [], contact: null, end: 'unchanged position; posture standing or implied_seated', affects: ['agent'], handoff: ['pos', 'posture'], validation: ['no_displacement', 'implied_seated_warning'], engine: [{ action: 'arms_crossed' }, { action: 'idle' }], framing: ['waist_up_if_implied_seated'] }),
  warning: c({ id: 'warning', entities: ['agent', 'target'], preconditions: ['agent_standing_or_seated'], start: 'standing', bridge: null, trajectory: 'in_place', durationSec: [0.7, 1.2], events: [], contact: null, end: 'unchanged; lookTarget = target', affects: ['agent'], handoff: ['lookTarget', 'expression'], validation: ['no_displacement'], engine: [{ action: 'head_shake' }], framing: ['face', 'target'] }),
  move_to: c({ id: 'move_to', entities: ['agent', 'mark'], preconditions: ['agent_standing', 'path_clear'], start: 'standing anywhere', bridge: null, trajectory: 'path', durationSec: [0.3, 8], events: ['reached_mark'], contact: null, end: 'standing at mark, facing the mark facing', affects: ['agent'], handoff: ['pos', 'yaw', 'mark'], validation: ['continuous_path', 'speed<=1.1m/s', 'end_at_mark<=0.02m'], engine: [{ action: 'walk', note: 'to = mark' }], framing: ['full_body_if_long'] }),
  press_button: c({ id: 'press_button', entities: ['agent', 'prop:button'], preconditions: ['agent_standing', 'within_reach(0.55m)', 'facing_button(<=25deg)'], start: 'standing within reach, facing the button', bridge: 'turn_toward', trajectory: 'in_place', durationSec: [0.8, 1.0], events: ['press_contact'], contact: { between: ['agent.hand', 'button.press_surface'], rule: 'at u=0.42 of the press', once: true }, end: 'button pressed (cap depth 1)', affects: ['agent', 'button'], handoff: ['button.capDepth'], validation: ['contact_once', 'no_teleport_to_button'], engine: [{ action: 'press_button', note: 'target button.press_surface' }, { propEvent: 'press' }], framing: ['hands', 'prop:button'] }),
  spawn_coin: c({ id: 'spawn_coin', entities: ['prop:coin', 'prop:button', 'mark:coin_spawn'], preconditions: ['press_contact_within_0.2s', 'coin_hidden'], start: 'coin hidden inside the button', bridge: null, trajectory: 'ballistic', durationSec: [0.9, 1.1], events: ['coin_spawn', 'coin_land'], contact: { between: ['coin', 'floor'], rule: 'lands once at coin_spawn', once: true }, end: 'coin resting flat at coin_spawn, scale 1', affects: ['coin'], handoff: ['coin.pos', 'coin.basePoint'], validation: ['lands_at_coin_spawn<=0.01m'], engine: [{ propEvent: 'spawn', note: 'from button.spawn_point to coin_spawn' }], framing: ['prop:coin'] }),
  grow_coin: c({ id: 'grow_coin', entities: ['prop:coin'], preconditions: ['coin_visible', 'coin_on_floor_at_base'], start: 'resting or upright at its base point', bridge: null, trajectory: 'scale_about_base', durationSec: [0.3, 0.6], events: ['coin_stand', 'grow_step'], contact: null, end: 'upright at the same base point, larger scale', affects: ['coin'], handoff: ['coin.scale', 'coin.upright'], validation: ['base_drift<=0.01m', 'scale_continuous', 'uniform_scale'], engine: [{ propEvent: 'stand_up' }, { propEvent: 'grow' }], framing: ['prop:coin', 'scale_reference'] }),
  move_safely: c({ id: 'move_safely', entities: ['agent', 'mark:*_safe'], preconditions: ['agent_standing', 'path_clear', 'hazard_exists'], start: 'at the agent desk mark', bridge: null, trajectory: 'path', durationSec: [0.8, 6], events: ['reached_safe'], contact: null, end: 'standing at the safe mark, outside every hazard volume + 0.5 m', affects: ['agent'], handoff: ['pos', 'mark', 'safe'], validation: ['displacement>=1.0m', 'end_at_safe<=0.02m', 'outside_hazard_at_contact'], engine: [{ action: 'walk', note: 'to = safe mark' }], framing: ['full_body', 'hazard_in_frame'] }),
  confident_pose: c({ id: 'confident_pose', entities: ['agent'], preconditions: ['agent_standing'], start: 'standing (at zapp_impact when a tip follows)', bridge: null, trajectory: 'in_place', durationSec: [0.8, 10], events: [], contact: null, end: 'standing, facing the audience', affects: ['agent'], handoff: ['pose'], validation: ['no_displacement'], engine: [{ action: 'arms_crossed' }], framing: ['waist_up', 'hazard_behind'] }),
  tip_coin_onto: c({ id: 'tip_coin_onto', entities: ['prop:coin', 'patient', 'mark:zapp_impact'], preconditions: ['coin_visible', 'coin_upright', 'coin_at_base', 'patient_at_zapp_impact', 'others_at_safe_marks'], start: 'upright giant coin at its base; patient standing at zapp_impact; others safe', bridge: null, trajectory: 'pivot_bottom_front_edge', durationSec: [1.2, 2.0], events: ['tip_start', 'coin_patient_contact', 'coin_rest'], contact: { between: ['coin', 'patient'], rule: 'first touch of the coin solid and the patient body; then maintained (no bounce)', once: true }, end: 'coin resting on the prone patient, face tilted above the floor', affects: ['coin', 'patient'], handoff: ['coin.transform', 'patient.posture'], validation: ['contact_count==1', 'monotonic_rotation', 'pivot_fixed', 'no_penetration', 'thickness_ratio_constant'], engine: [{ propEvent: 'tip_over', note: 'endDeg from the contact solve (Checkpoint 2)' }], framing: ['wide', 'patient', 'coin'] }),
  fall_prone: c({ id: 'fall_prone', entities: ['patient', 'prop:coin'], preconditions: ['contact_occurred'], start: 'standing at zapp_impact at the contact instant', bridge: null, trajectory: 'coupled_fall', durationSec: [0.5, 0.8], events: ['patient_prone'], contact: { between: ['patient', 'coin'], rule: 'maintained from first contact', once: true }, end: 'prone, feet fixed at zapp_impact, head outside the coin; held to episode end', affects: ['patient'], handoff: ['posture=prone (no get_up)'], validation: ['starts_at_contact', 'continuous_pitch', 'prone_to_end'], engine: [{ action: 'dive_prone', note: 'procedural coupled blend in Checkpoint 2' }], framing: ['patient_face_visible'] }),
  reset_button: c({ id: 'reset_button', entities: ['prop:button'], preconditions: ['button_pressed_before'], start: 'button pressed', bridge: null, trajectory: 'state_only', durationSec: [0.3, 0.4], events: ['button_reset'], contact: null, end: 'button idle and armed (cap depth 0, glowing)', affects: ['button'], handoff: ['button.phase=reset'], validation: ['world_consequences_unchanged'], engine: [{ propEvent: 'reset' }, { propEvent: 'flash' }], framing: ['prop:button'] }),
  off_screen_teacher_cue: c({ id: 'off_screen_teacher_cue', entities: ['offscreen', 'mark:classroom_door'], preconditions: ['person_unavailable'], start: 'person off-screen at classroom_door', bridge: null, trajectory: 'none', durationSec: [0, 0], events: ['offscreen_cue'], contact: null, end: 'latest cue recorded; never instantiated', affects: ['offscreen'], handoff: ['offscreen.latestCue'], validation: ['never_an_actor'], engine: [{ note: 'door sound cue + look toward classroom_door (no mesh, no character)' }], framing: ['never_frame_classroom_door'] }),
};

export interface ContractInstance { id: string; contract: ContractId; actor: string | null; prop: string | null; t0: number; t1: number; phraseId: string | null; bridgeFor: string | null; params: Record<string, string | number> }
export interface Bridge { id: string; contract: ContractId; actor: string; reason: string; forContract: string; t0: number; t1: number; from: [number, number, number]; to: [number, number, number] }
export interface PlanError { code: string; contract: ContractId; phraseId: string | null; t: number; message: string }
