// Generated by scripts/generate-lib-set-manifests.ts. Do not hand-edit; regenerate deterministically.
import type { EnvironmentManifest } from '../../../schema/src/assets.ts';

export const CLASSROOM_MANIFEST = {
  "kind": "environment",
  "id": "classroom",
  "version": "1.2.0",
  "displayName": "Classroom 1A - Doorway",
  "units": "meters",
  "axes": {
    "up": "+y",
    "stageRight": "+x",
    "towardAudience": "+z"
  },
  "bounds": {
    "min": [
      -4.6,
      0,
      -4.1
    ],
    "max": [
      4.6,
      4.2,
      4
    ]
  },
  "pieces": [
    {
      "id": "floor",
      "size": [
        9.2,
        0.1,
        14.2
      ],
      "pos": [
        0,
        -0.05,
        2.95
      ],
      "color": "#ffffff",
      "texture": "floor_planks",
      "collide": true
    },
    {
      "id": "wall_back_left",
      "size": [
        6.4,
        4.2,
        0.2
      ],
      "pos": [
        -1.4,
        2.1,
        -4.1
      ],
      "color": "#9fcbb6",
      "collide": true
    },
    {
      "id": "wall_back_right",
      "size": [
        1.4,
        4.2,
        0.2
      ],
      "pos": [
        3.9,
        2.1,
        -4.1
      ],
      "color": "#9fcbb6",
      "collide": true
    },
    {
      "id": "wall_back_lintel",
      "size": [
        1.4,
        1.15,
        0.2
      ],
      "pos": [
        2.5,
        3.625,
        -4.1
      ],
      "color": "#9fcbb6",
      "collide": true
    },
    {
      "id": "wainscot_back_left",
      "size": [
        6.4,
        1,
        0.06
      ],
      "pos": [
        -1.4,
        0.5,
        -3.98
      ],
      "color": "#5f8f7a",
      "collide": false
    },
    {
      "id": "wainscot_back_right",
      "size": [
        1.4,
        1,
        0.06
      ],
      "pos": [
        3.9,
        0.5,
        -3.98
      ],
      "color": "#5f8f7a",
      "collide": false
    },
    {
      "id": "rail_back_left",
      "size": [
        6.4,
        0.06,
        0.1
      ],
      "pos": [
        -1.4,
        1.02,
        -3.96
      ],
      "color": "#e9e1cf",
      "collide": false,
      "bevel": 0.01
    },
    {
      "id": "rail_back_right",
      "size": [
        1.4,
        0.06,
        0.1
      ],
      "pos": [
        3.9,
        1.02,
        -3.96
      ],
      "color": "#e9e1cf",
      "collide": false,
      "bevel": 0.01
    },
    {
      "id": "classroom_door_frame_left",
      "size": [
        0.12,
        3.05,
        0.18
      ],
      "pos": [
        1.74,
        1.525,
        -3.96
      ],
      "color": "#f3ead4",
      "collide": false,
      "bevel": 0.015
    },
    {
      "id": "classroom_door_frame_right",
      "size": [
        0.12,
        3.05,
        0.18
      ],
      "pos": [
        3.26,
        1.525,
        -3.96
      ],
      "color": "#f3ead4",
      "collide": false,
      "bevel": 0.015
    },
    {
      "id": "classroom_door_frame_header",
      "size": [
        1.64,
        0.12,
        0.18
      ],
      "pos": [
        2.5,
        3.11,
        -3.96
      ],
      "color": "#f3ead4",
      "collide": false,
      "bevel": 0.015
    },
    {
      "id": "classroom_door_threshold",
      "size": [
        1.4,
        0.035,
        0.3
      ],
      "pos": [
        2.5,
        0.0175,
        -3.95
      ],
      "color": "#b18b61",
      "collide": false,
      "bevel": 0.008
    },
    {
      "id": "classroom_room_sign",
      "size": [
        0.72,
        0.28,
        0.06
      ],
      "pos": [
        3.65,
        2.72,
        -3.96
      ],
      "color": "#264f73",
      "collide": false,
      "bevel": 0.025,
      "decor": true
    },
    {
      "id": "wall_left",
      "size": [
        0.2,
        4.2,
        8.2
      ],
      "pos": [
        -4.7,
        2.1,
        -0.05
      ],
      "color": "#b7d7c6",
      "collide": true
    },
    {
      "id": "wall_right",
      "size": [
        0.2,
        4.2,
        8.2
      ],
      "pos": [
        4.7,
        2.1,
        -0.05
      ],
      "color": "#b7d7c6",
      "collide": true
    },
    {
      "id": "wainscot_left",
      "size": [
        0.06,
        1,
        8.2
      ],
      "pos": [
        -4.58,
        0.5,
        -0.05
      ],
      "color": "#5f8f7a",
      "collide": false
    },
    {
      "id": "wainscot_right",
      "size": [
        0.06,
        1,
        8.2
      ],
      "pos": [
        4.58,
        0.5,
        -0.05
      ],
      "color": "#5f8f7a",
      "collide": false
    },
    {
      "id": "window_l1",
      "shape": "plane",
      "size": [
        1.6,
        1.5,
        0
      ],
      "pos": [
        -4.585,
        2.1,
        -2.2
      ],
      "rotDeg": [
        0,
        90,
        0
      ],
      "color": "#ffffff",
      "texture": "window_sky",
      "emissive": "#cfe8ff",
      "collide": false
    },
    {
      "id": "window_l2",
      "shape": "plane",
      "size": [
        1.6,
        1.5,
        0
      ],
      "pos": [
        -4.585,
        2.1,
        0.6
      ],
      "rotDeg": [
        0,
        90,
        0
      ],
      "color": "#ffffff",
      "texture": "window_sky",
      "emissive": "#cfe8ff",
      "collide": false
    },
    {
      "id": "window_l1_sill",
      "size": [
        0.18,
        0.06,
        1.8
      ],
      "pos": [
        -4.52,
        1.32,
        -2.2
      ],
      "color": "#f2ede0",
      "bevel": 0.01,
      "collide": false
    },
    {
      "id": "window_l2_sill",
      "size": [
        0.18,
        0.06,
        1.8
      ],
      "pos": [
        -4.52,
        1.32,
        0.6
      ],
      "color": "#f2ede0",
      "bevel": 0.01,
      "collide": false
    },
    {
      "id": "board_frame",
      "size": [
        3.5,
        1.55,
        0.08
      ],
      "pos": [
        0,
        2,
        -3.97
      ],
      "color": "#b27c46",
      "bevel": 0.02,
      "collide": false
    },
    {
      "id": "chalkboard",
      "shape": "plane",
      "size": [
        3.3,
        1.35,
        0
      ],
      "pos": [
        0,
        2,
        -3.925
      ],
      "color": "#ffffff",
      "texture": "chalkboard",
      "collide": false
    },
    {
      "id": "chalk_tray",
      "size": [
        3.3,
        0.05,
        0.12
      ],
      "pos": [
        0,
        1.2,
        -3.9
      ],
      "color": "#b27c46",
      "collide": false
    },
    {
      "id": "clock_body",
      "shape": "cylinder",
      "size": [
        0.26,
        0.06,
        0
      ],
      "pos": [
        3.75,
        3.15,
        -3.97
      ],
      "rotDeg": [
        90,
        0,
        0
      ],
      "color": "#ffffff",
      "texture": "clock_face",
      "collide": false,
      "decor": true
    },
    {
      "id": "poster_read",
      "shape": "plane",
      "size": [
        0.8,
        1.05,
        0
      ],
      "pos": [
        -2.7,
        2.2,
        -3.99
      ],
      "color": "#ffffff",
      "texture": "poster_read",
      "collide": false,
      "decor": true
    },
    {
      "id": "poster_planets",
      "shape": "plane",
      "size": [
        0.9,
        0.9,
        0
      ],
      "pos": [
        4.585,
        2.3,
        -1.8
      ],
      "rotDeg": [
        0,
        -90,
        0
      ],
      "color": "#ffffff",
      "texture": "poster_planet",
      "collide": false,
      "decor": true
    },
    {
      "id": "teacher_desk_top",
      "size": [
        1.7,
        0.08,
        0.8
      ],
      "pos": [
        -2.7,
        0.8,
        -2.9
      ],
      "color": "#8a5a36",
      "bevel": 0.015,
      "collide": true
    },
    {
      "id": "teacher_desk_body",
      "size": [
        1.6,
        0.76,
        0.7
      ],
      "pos": [
        -2.7,
        0.38,
        -2.9
      ],
      "color": "#6e4428",
      "bevel": 0.01,
      "collide": true
    },
    {
      "id": "teacher_apple",
      "shape": "sphere",
      "size": [
        0.06,
        0,
        0
      ],
      "pos": [
        -2.2,
        0.9,
        -2.8
      ],
      "color": "#e0312d",
      "collide": false,
      "decor": true
    },
    {
      "id": "books_stack",
      "size": [
        0.3,
        0.14,
        0.22
      ],
      "pos": [
        -3.2,
        0.91,
        -2.85
      ],
      "color": "#3d63c9",
      "bevel": 0.01,
      "collide": false,
      "decor": true
    },
    {
      "id": "bg_desk_1_top",
      "size": [
        1,
        0.05,
        0.62
      ],
      "pos": [
        -1.35,
        0.735,
        -2.75
      ],
      "color": "#d8ad72",
      "bevel": 0.012,
      "collide": true
    },
    {
      "id": "bg_desk_1_apron",
      "size": [
        0.94,
        0.12,
        0.56
      ],
      "pos": [
        -1.35,
        0.65,
        -2.75
      ],
      "color": "#5d7fa3",
      "collide": true
    },
    {
      "id": "bg_desk_2_top",
      "size": [
        1,
        0.05,
        0.62
      ],
      "pos": [
        1.45,
        0.735,
        -2.3
      ],
      "color": "#d8ad72",
      "bevel": 0.012,
      "collide": true
    },
    {
      "id": "bg_desk_2_apron",
      "size": [
        0.94,
        0.12,
        0.56
      ],
      "pos": [
        1.45,
        0.65,
        -2.3
      ],
      "color": "#5d7fa3",
      "collide": true
    },
    {
      "id": "bg_desk_3_top",
      "size": [
        1,
        0.05,
        0.62
      ],
      "pos": [
        3.1,
        0.735,
        -1.2
      ],
      "color": "#d8ad72",
      "bevel": 0.012,
      "collide": true
    },
    {
      "id": "bg_desk_3_apron",
      "size": [
        0.94,
        0.12,
        0.56
      ],
      "pos": [
        3.1,
        0.65,
        -1.2
      ],
      "color": "#5d7fa3",
      "collide": true
    },
    {
      "id": "bg_desk_4_top",
      "size": [
        1,
        0.05,
        0.62
      ],
      "pos": [
        -3.2,
        0.735,
        -2.75
      ],
      "color": "#d8ad72",
      "bevel": 0.012,
      "collide": true
    },
    {
      "id": "bg_desk_4_apron",
      "size": [
        0.94,
        0.12,
        0.56
      ],
      "pos": [
        -3.2,
        0.65,
        -2.75
      ],
      "color": "#5d7fa3",
      "collide": true
    },
    {
      "id": "bg_desk_legs_1",
      "size": [
        0.9,
        0.6,
        0.5
      ],
      "pos": [
        -1.35,
        0.3,
        -2.75
      ],
      "color": "#4a5563",
      "collide": true,
      "decor": true
    },
    {
      "id": "bg_desk_legs_2",
      "size": [
        0.9,
        0.6,
        0.5
      ],
      "pos": [
        1.45,
        0.3,
        -2.3
      ],
      "color": "#4a5563",
      "collide": true,
      "decor": true
    },
    {
      "id": "bg_desk_legs_3",
      "size": [
        0.9,
        0.6,
        0.5
      ],
      "pos": [
        3.1,
        0.3,
        -1.2
      ],
      "color": "#4a5563",
      "collide": true,
      "decor": true
    },
    {
      "id": "bg_desk_legs_4",
      "size": [
        0.9,
        0.6,
        0.5
      ],
      "pos": [
        -3.2,
        0.3,
        -2.75
      ],
      "color": "#4a5563",
      "collide": true,
      "decor": true
    },
    {
      "id": "bg_chair_2_seat",
      "size": [
        0.44,
        0.05,
        0.42
      ],
      "pos": [
        1.45,
        0.45,
        -1.75
      ],
      "color": "#e0653a",
      "bevel": 0.012,
      "collide": true
    },
    {
      "id": "bg_chair_2_back",
      "size": [
        0.44,
        0.42,
        0.05
      ],
      "pos": [
        1.45,
        0.72,
        -1.52
      ],
      "color": "#e0653a",
      "bevel": 0.012,
      "collide": true
    },
    {
      "id": "bg_chair_legs_2",
      "size": [
        0.36,
        0.43,
        0.36
      ],
      "pos": [
        1.45,
        0.215,
        -1.75
      ],
      "color": "#4a5563",
      "collide": true,
      "decor": true
    },
    {
      "id": "shelf",
      "size": [
        0.4,
        1.3,
        1.8
      ],
      "pos": [
        4.38,
        0.65,
        1.2
      ],
      "color": "#8a5a36",
      "bevel": 0.015,
      "collide": true
    },
    {
      "id": "shelf_books_a",
      "size": [
        0.3,
        0.26,
        0.7
      ],
      "pos": [
        4.3,
        1.1,
        0.8
      ],
      "color": "#e0312d",
      "bevel": 0.01,
      "collide": false,
      "decor": true
    },
    {
      "id": "shelf_books_b",
      "size": [
        0.3,
        0.22,
        0.6
      ],
      "pos": [
        4.3,
        1.1,
        1.55
      ],
      "color": "#ffc21a",
      "bevel": 0.01,
      "collide": false,
      "decor": true
    },
    {
      "id": "shelf_books_c",
      "size": [
        0.3,
        0.24,
        0.9
      ],
      "pos": [
        4.3,
        0.55,
        1.2
      ],
      "color": "#3d63c9",
      "bevel": 0.01,
      "collide": false,
      "decor": true
    },
    {
      "id": "plant_pot",
      "shape": "cylinder",
      "size": [
        0.16,
        0.3,
        0
      ],
      "pos": [
        -4.25,
        0.15,
        2.4
      ],
      "color": "#c46a3c",
      "collide": true,
      "decor": true
    },
    {
      "id": "plant_leaves",
      "shape": "sphere",
      "size": [
        0.32,
        0,
        0
      ],
      "pos": [
        -4.25,
        0.55,
        2.4
      ],
      "color": "#3c9a52",
      "collide": false,
      "decor": true
    },
    {
      "id": "ceiling_trim",
      "size": [
        9.2,
        0.12,
        0.3
      ],
      "pos": [
        0,
        4.14,
        -3.9
      ],
      "color": "#e9e1cf",
      "collide": false
    }
  ],
  "marks": {
    "zapp_enter": {
      "pos": [
        -0.75,
        0,
        -1.9
      ],
      "facingDeg": 40
    },
    "zapp_desk": {
      "pos": [
        0.25,
        0,
        -0.52
      ],
      "facingDeg": 0
    },
    "zapp_flee": {
      "pos": [
        -1.5,
        0,
        0.75
      ],
      "facingDeg": 0
    },
    "kira_desk": {
      "pos": [
        1.3,
        0,
        -0.35
      ],
      "facingDeg": -50
    },
    "kira_safe": {
      "pos": [
        2.5,
        0,
        0.6
      ],
      "facingDeg": 20
    },
    "center_stage": {
      "pos": [
        0,
        0,
        0.5
      ],
      "facingDeg": 0
    },
    "coin_front": {
      "pos": [
        -1.5,
        0,
        -0.3
      ],
      "facingDeg": 0
    },
    "enter_back_left": {
      "pos": [
        -0.75,
        0,
        -1.9
      ],
      "facingDeg": 40
    },
    "press_spot": {
      "pos": [
        0.25,
        0,
        -0.52
      ],
      "facingDeg": 0
    },
    "foil_spot": {
      "pos": [
        1.3,
        0,
        -0.35
      ],
      "facingDeg": -50
    },
    "foil_safe": {
      "pos": [
        2.5,
        0,
        0.6
      ],
      "facingDeg": 20
    },
    "watch_right": {
      "pos": [
        1.15,
        0,
        -1
      ],
      "facingDeg": -40
    },
    "giant_front": {
      "pos": [
        -2,
        0,
        -0.75
      ],
      "facingDeg": 0
    },
    "dive_end": {
      "pos": [
        -2,
        0,
        0.3
      ],
      "facingDeg": 0
    },
    "race_left": {
      "pos": [
        -2.1,
        0,
        -1.25
      ],
      "facingDeg": 70
    },
    "race_right": {
      "pos": [
        2.4,
        0,
        0.9
      ],
      "facingDeg": -100
    },
    "wp_desk_back_left": {
      "pos": [
        -0.6,
        0,
        -0.85
      ],
      "facingDeg": -110
    },
    "wp_desk_back_right": {
      "pos": [
        0.95,
        0,
        -0.9
      ],
      "facingDeg": -60
    },
    "wp_front_left": {
      "pos": [
        -0.95,
        0,
        0.75
      ],
      "facingDeg": 0
    },
    "wp_front_right": {
      "pos": [
        0.95,
        0,
        0.75
      ],
      "facingDeg": 0
    },
    "press_left": {
      "pos": [
        -0.45,
        0,
        -0.52
      ],
      "facingDeg": 0
    },
    "watch_left": {
      "pos": [
        -1.25,
        0,
        -0.95
      ],
      "facingDeg": 50
    },
    "observe_safe": {
      "pos": [
        1.15,
        0,
        0.45
      ],
      "facingDeg": -60
    },
    "smart_wait": {
      "pos": [
        -0.55,
        0,
        -0.95
      ],
      "facingDeg": 60
    },
    "classroom_door_inside": {
      "pos": [
        2.5,
        0,
        -3
      ],
      "facingDeg": 0
    }
  },
  "anchors": {
    "hero_desk_spot": [
      0,
      0,
      0
    ],
    "coin_floor": [
      -2.1,
      0,
      -1.4
    ],
    "board_center": [
      0,
      2,
      -3.92
    ],
    "zapp_look_up": [
      -1.6,
      3,
      -0.8
    ],
    "look_up_point": [
      -2.1,
      3,
      -1.5
    ],
    "giant_spot": [
      -2.2,
      0,
      -1.8
    ]
  },
  "cameraSafe": {
    "min": [
      -4.3,
      0.15,
      -3.6
    ],
    "max": [
      4.3,
      4,
      14
    ],
    "audienceSideOnly": true
  },
  "composition": {
    "actionSafe": {
      "left": 0.06,
      "right": 0.86,
      "top": 0.1,
      "bottom": 0.8
    },
    "stageLine": {
      "a": [
        -3,
        0,
        0.4
      ],
      "b": [
        3,
        0,
        0.4
      ]
    }
  },
  "lighting": {
    "morning": {
      "sunDir": [
        -0.72,
        0.78,
        0.42
      ],
      "sunColor": "#fff1d9",
      "sunIntensity": 2.1,
      "sky": "#c9dcf2",
      "ground": "#b08a62",
      "ambientIntensity": 0.62,
      "fog": "#e7eef2",
      "fogNear": 18,
      "fogFar": 45,
      "exposure": 1.05
    },
    "afternoon": {
      "sunDir": [
        0.62,
        0.74,
        0.28
      ],
      "sunColor": "#ffe2b8",
      "sunIntensity": 1.75,
      "sky": "#b9d2e8",
      "ground": "#a27a58",
      "ambientIntensity": 0.7,
      "fog": "#e8e2d7",
      "fogNear": 18,
      "fogFar": 46,
      "exposure": 1.02
    }
  },
  "extras": {
    "decorDensity": 1,
    "backgroundCharacters": 0
  },
  "license": {
    "source": "original-procedural",
    "author": "RBLX SPARK (in-house)",
    "license": "Proprietary - owned",
    "attributionRequired": false,
    "notes": "All posters, chalk doodles and textures are procedurally drawn in-house."
  },
  "notes": "1.2.0: preserves 1.1.0 geometry while adding a collision-clear 1.40m x 3.05m doorway and the approved narrated coin/impact staging coordinates."
} as unknown as EnvironmentManifest;
export const SCHOOL_HALLWAY_MANIFEST = {
  "kind": "environment",
  "id": "school_hallway",
  "version": "1.0.0",
  "displayName": "North School Hall",
  "units": "meters",
  "axes": {
    "up": "+y",
    "stageRight": "+x",
    "towardAudience": "+z"
  },
  "bounds": {
    "min": [
      -4.6,
      0,
      -8.2
    ],
    "max": [
      4.6,
      4.2,
      8.2
    ]
  },
  "pieces": [
    {
      "id": "floor",
      "size": [
        9.2,
        0.1,
        16.4
      ],
      "pos": [
        0,
        -0.05,
        0
      ],
      "color": "#d8d2c4",
      "collide": true,
      "bevel": 0.01
    },
    {
      "id": "ceiling",
      "size": [
        9.2,
        0.1,
        16.4
      ],
      "pos": [
        0,
        4.15,
        0
      ],
      "color": "#f4f0e8",
      "collide": false
    },
    {
      "id": "wall_left",
      "size": [
        0.2,
        4.2,
        16.4
      ],
      "pos": [
        -4.6,
        2.1,
        0
      ],
      "color": "#c9d9df",
      "collide": true
    },
    {
      "id": "wall_right",
      "size": [
        0.2,
        4.2,
        16.4
      ],
      "pos": [
        4.6,
        2.1,
        0
      ],
      "color": "#c9d9df",
      "collide": true
    },
    {
      "id": "wall_back_left",
      "size": [
        3.9,
        4.2,
        0.2
      ],
      "pos": [
        -2.65,
        2.1,
        -8.2
      ],
      "color": "#b9ced7",
      "collide": true
    },
    {
      "id": "wall_back_right",
      "size": [
        3.9,
        4.2,
        0.2
      ],
      "pos": [
        2.65,
        2.1,
        -8.2
      ],
      "color": "#b9ced7",
      "collide": true
    },
    {
      "id": "wall_back_lintel",
      "size": [
        1.4,
        1.15,
        0.2
      ],
      "pos": [
        0,
        3.625,
        -8.2
      ],
      "color": "#b9ced7",
      "collide": true
    },
    {
      "id": "wall_front",
      "size": [
        9.2,
        4.2,
        0.2
      ],
      "pos": [
        0,
        2.1,
        8.2
      ],
      "color": "#d4e0e4",
      "collide": true
    },
    {
      "id": "baseboard_left",
      "size": [
        0.08,
        0.24,
        16
      ],
      "pos": [
        -4.47,
        0.12,
        0
      ],
      "color": "#426b78",
      "collide": false
    },
    {
      "id": "baseboard_right",
      "size": [
        0.08,
        0.24,
        16
      ],
      "pos": [
        4.47,
        0.12,
        0
      ],
      "color": "#426b78",
      "collide": false
    },
    {
      "id": "hall_door_frame_left",
      "size": [
        0.12,
        3.05,
        0.18
      ],
      "pos": [
        -0.76,
        1.525,
        -8.06
      ],
      "color": "#f4e2b8",
      "collide": false,
      "bevel": 0.015
    },
    {
      "id": "hall_door_frame_right",
      "size": [
        0.12,
        3.05,
        0.18
      ],
      "pos": [
        0.76,
        1.525,
        -8.06
      ],
      "color": "#f4e2b8",
      "collide": false,
      "bevel": 0.015
    },
    {
      "id": "hall_door_frame_header",
      "size": [
        1.64,
        0.12,
        0.18
      ],
      "pos": [
        0,
        3.11,
        -8.06
      ],
      "color": "#f4e2b8",
      "collide": false,
      "bevel": 0.015
    },
    {
      "id": "hall_door_threshold",
      "size": [
        1.4,
        0.035,
        0.32
      ],
      "pos": [
        0,
        0.0175,
        -8.05
      ],
      "color": "#9b8064",
      "collide": false,
      "bevel": 0.008
    },
    {
      "id": "hall_door_exit_sign",
      "size": [
        0.8,
        0.28,
        0.08
      ],
      "pos": [
        0,
        3.45,
        -8.05
      ],
      "color": "#2f8b57",
      "collide": false,
      "emissive": "#58d68d"
    },
    {
      "id": "water_fountain",
      "size": [
        0.55,
        0.85,
        0.52
      ],
      "pos": [
        4.15,
        0.425,
        -2.3
      ],
      "color": "#7396a7",
      "collide": true,
      "bevel": 0.06
    },
    {
      "id": "water_fountain_basin",
      "size": [
        0.62,
        0.12,
        0.62
      ],
      "pos": [
        4.05,
        0.88,
        -2.3
      ],
      "color": "#a9c2cd",
      "collide": false,
      "bevel": 0.04
    },
    {
      "id": "trophy_case",
      "size": [
        0.4,
        1.7,
        2.5
      ],
      "pos": [
        4.25,
        1.15,
        3.7
      ],
      "color": "#89633f",
      "collide": true,
      "bevel": 0.03
    },
    {
      "id": "trophy_case_glass",
      "size": [
        0.05,
        1.42,
        2.22
      ],
      "pos": [
        4.02,
        1.2,
        3.7
      ],
      "color": "#9ed7df",
      "collide": false,
      "emissive": "#bcebf2"
    },
    {
      "id": "hall_center_stripe",
      "size": [
        0.08,
        0.012,
        14.5
      ],
      "pos": [
        0,
        0.012,
        0
      ],
      "color": "#e9b949",
      "collide": false
    },
    {
      "id": "locker_1",
      "size": [
        0.48,
        1.9,
        1
      ],
      "pos": [
        -4.22,
        0.95,
        -5.4
      ],
      "color": "#2f7896",
      "collide": true,
      "bevel": 0.025
    },
    {
      "id": "locker_door_1",
      "size": [
        0.035,
        1.72,
        0.9
      ],
      "pos": [
        -3.965,
        0.98,
        -5.4
      ],
      "color": "#438eaa",
      "collide": false,
      "bevel": 0.018
    },
    {
      "id": "locker_vent_1",
      "size": [
        0.025,
        0.05,
        0.42
      ],
      "pos": [
        -3.942,
        1.58,
        -5.4
      ],
      "color": "#173c52",
      "collide": false
    },
    {
      "id": "locker_handle_1",
      "size": [
        0.035,
        0.18,
        0.05
      ],
      "pos": [
        -3.93,
        1.02,
        -5.130000000000001
      ],
      "color": "#e2d4aa",
      "collide": false,
      "bevel": 0.01
    },
    {
      "id": "locker_2",
      "size": [
        0.48,
        1.9,
        1
      ],
      "pos": [
        -4.22,
        0.95,
        -4.2
      ],
      "color": "#356b8c",
      "collide": true,
      "bevel": 0.025
    },
    {
      "id": "locker_door_2",
      "size": [
        0.035,
        1.72,
        0.9
      ],
      "pos": [
        -3.965,
        0.98,
        -4.2
      ],
      "color": "#4c88a9",
      "collide": false,
      "bevel": 0.018
    },
    {
      "id": "locker_vent_2",
      "size": [
        0.025,
        0.05,
        0.42
      ],
      "pos": [
        -3.942,
        1.58,
        -4.2
      ],
      "color": "#173c52",
      "collide": false
    },
    {
      "id": "locker_handle_2",
      "size": [
        0.035,
        0.18,
        0.05
      ],
      "pos": [
        -3.93,
        1.02,
        -3.93
      ],
      "color": "#e2d4aa",
      "collide": false,
      "bevel": 0.01
    },
    {
      "id": "locker_3",
      "size": [
        0.48,
        1.9,
        1
      ],
      "pos": [
        -4.22,
        0.95,
        -3.0000000000000004
      ],
      "color": "#2f7896",
      "collide": true,
      "bevel": 0.025
    },
    {
      "id": "locker_door_3",
      "size": [
        0.035,
        1.72,
        0.9
      ],
      "pos": [
        -3.965,
        0.98,
        -3.0000000000000004
      ],
      "color": "#438eaa",
      "collide": false,
      "bevel": 0.018
    },
    {
      "id": "locker_vent_3",
      "size": [
        0.025,
        0.05,
        0.42
      ],
      "pos": [
        -3.942,
        1.58,
        -3.0000000000000004
      ],
      "color": "#173c52",
      "collide": false
    },
    {
      "id": "locker_handle_3",
      "size": [
        0.035,
        0.18,
        0.05
      ],
      "pos": [
        -3.93,
        1.02,
        -2.7300000000000004
      ],
      "color": "#e2d4aa",
      "collide": false,
      "bevel": 0.01
    },
    {
      "id": "locker_4",
      "size": [
        0.48,
        1.9,
        1
      ],
      "pos": [
        -4.22,
        0.95,
        -1.8000000000000007
      ],
      "color": "#356b8c",
      "collide": true,
      "bevel": 0.025
    },
    {
      "id": "locker_door_4",
      "size": [
        0.035,
        1.72,
        0.9
      ],
      "pos": [
        -3.965,
        0.98,
        -1.8000000000000007
      ],
      "color": "#4c88a9",
      "collide": false,
      "bevel": 0.018
    },
    {
      "id": "locker_vent_4",
      "size": [
        0.025,
        0.05,
        0.42
      ],
      "pos": [
        -3.942,
        1.58,
        -1.8000000000000007
      ],
      "color": "#173c52",
      "collide": false
    },
    {
      "id": "locker_handle_4",
      "size": [
        0.035,
        0.18,
        0.05
      ],
      "pos": [
        -3.93,
        1.02,
        -1.5300000000000007
      ],
      "color": "#e2d4aa",
      "collide": false,
      "bevel": 0.01
    },
    {
      "id": "locker_5",
      "size": [
        0.48,
        1.9,
        1
      ],
      "pos": [
        -4.22,
        0.95,
        -0.6000000000000005
      ],
      "color": "#2f7896",
      "collide": true,
      "bevel": 0.025
    },
    {
      "id": "locker_door_5",
      "size": [
        0.035,
        1.72,
        0.9
      ],
      "pos": [
        -3.965,
        0.98,
        -0.6000000000000005
      ],
      "color": "#438eaa",
      "collide": false,
      "bevel": 0.018
    },
    {
      "id": "locker_vent_5",
      "size": [
        0.025,
        0.05,
        0.42
      ],
      "pos": [
        -3.942,
        1.58,
        -0.6000000000000005
      ],
      "color": "#173c52",
      "collide": false
    },
    {
      "id": "locker_handle_5",
      "size": [
        0.035,
        0.18,
        0.05
      ],
      "pos": [
        -3.93,
        1.02,
        -0.3300000000000005
      ],
      "color": "#e2d4aa",
      "collide": false,
      "bevel": 0.01
    },
    {
      "id": "locker_6",
      "size": [
        0.48,
        1.9,
        1
      ],
      "pos": [
        -4.22,
        0.95,
        0.5999999999999996
      ],
      "color": "#356b8c",
      "collide": true,
      "bevel": 0.025
    },
    {
      "id": "locker_door_6",
      "size": [
        0.035,
        1.72,
        0.9
      ],
      "pos": [
        -3.965,
        0.98,
        0.5999999999999996
      ],
      "color": "#4c88a9",
      "collide": false,
      "bevel": 0.018
    },
    {
      "id": "locker_vent_6",
      "size": [
        0.025,
        0.05,
        0.42
      ],
      "pos": [
        -3.942,
        1.58,
        0.5999999999999996
      ],
      "color": "#173c52",
      "collide": false
    },
    {
      "id": "locker_handle_6",
      "size": [
        0.035,
        0.18,
        0.05
      ],
      "pos": [
        -3.93,
        1.02,
        0.8699999999999997
      ],
      "color": "#e2d4aa",
      "collide": false,
      "bevel": 0.01
    },
    {
      "id": "locker_7",
      "size": [
        0.48,
        1.9,
        1
      ],
      "pos": [
        -4.22,
        0.95,
        1.799999999999999
      ],
      "color": "#2f7896",
      "collide": true,
      "bevel": 0.025
    },
    {
      "id": "locker_door_7",
      "size": [
        0.035,
        1.72,
        0.9
      ],
      "pos": [
        -3.965,
        0.98,
        1.799999999999999
      ],
      "color": "#438eaa",
      "collide": false,
      "bevel": 0.018
    },
    {
      "id": "locker_vent_7",
      "size": [
        0.025,
        0.05,
        0.42
      ],
      "pos": [
        -3.942,
        1.58,
        1.799999999999999
      ],
      "color": "#173c52",
      "collide": false
    },
    {
      "id": "locker_handle_7",
      "size": [
        0.035,
        0.18,
        0.05
      ],
      "pos": [
        -3.93,
        1.02,
        2.069999999999999
      ],
      "color": "#e2d4aa",
      "collide": false,
      "bevel": 0.01
    },
    {
      "id": "locker_8",
      "size": [
        0.48,
        1.9,
        1
      ],
      "pos": [
        -4.22,
        0.95,
        3
      ],
      "color": "#356b8c",
      "collide": true,
      "bevel": 0.025
    },
    {
      "id": "locker_door_8",
      "size": [
        0.035,
        1.72,
        0.9
      ],
      "pos": [
        -3.965,
        0.98,
        3
      ],
      "color": "#4c88a9",
      "collide": false,
      "bevel": 0.018
    },
    {
      "id": "locker_vent_8",
      "size": [
        0.025,
        0.05,
        0.42
      ],
      "pos": [
        -3.942,
        1.58,
        3
      ],
      "color": "#173c52",
      "collide": false
    },
    {
      "id": "locker_handle_8",
      "size": [
        0.035,
        0.18,
        0.05
      ],
      "pos": [
        -3.93,
        1.02,
        3.27
      ],
      "color": "#e2d4aa",
      "collide": false,
      "bevel": 0.01
    },
    {
      "id": "locker_9",
      "size": [
        0.48,
        1.9,
        1
      ],
      "pos": [
        -4.22,
        0.95,
        4.199999999999999
      ],
      "color": "#2f7896",
      "collide": true,
      "bevel": 0.025
    },
    {
      "id": "locker_door_9",
      "size": [
        0.035,
        1.72,
        0.9
      ],
      "pos": [
        -3.965,
        0.98,
        4.199999999999999
      ],
      "color": "#438eaa",
      "collide": false,
      "bevel": 0.018
    },
    {
      "id": "locker_vent_9",
      "size": [
        0.025,
        0.05,
        0.42
      ],
      "pos": [
        -3.942,
        1.58,
        4.199999999999999
      ],
      "color": "#173c52",
      "collide": false
    },
    {
      "id": "locker_handle_9",
      "size": [
        0.035,
        0.18,
        0.05
      ],
      "pos": [
        -3.93,
        1.02,
        4.469999999999999
      ],
      "color": "#e2d4aa",
      "collide": false,
      "bevel": 0.01
    },
    {
      "id": "locker_10",
      "size": [
        0.48,
        1.9,
        1
      ],
      "pos": [
        -4.22,
        0.95,
        5.399999999999999
      ],
      "color": "#356b8c",
      "collide": true,
      "bevel": 0.025
    },
    {
      "id": "locker_door_10",
      "size": [
        0.035,
        1.72,
        0.9
      ],
      "pos": [
        -3.965,
        0.98,
        5.399999999999999
      ],
      "color": "#4c88a9",
      "collide": false,
      "bevel": 0.018
    },
    {
      "id": "locker_vent_10",
      "size": [
        0.025,
        0.05,
        0.42
      ],
      "pos": [
        -3.942,
        1.58,
        5.399999999999999
      ],
      "color": "#173c52",
      "collide": false
    },
    {
      "id": "locker_handle_10",
      "size": [
        0.035,
        0.18,
        0.05
      ],
      "pos": [
        -3.93,
        1.02,
        5.669999999999998
      ],
      "color": "#e2d4aa",
      "collide": false,
      "bevel": 0.01
    },
    {
      "id": "classroom_door_1",
      "size": [
        0.05,
        2.8,
        1.25
      ],
      "pos": [
        4.485,
        1.4,
        -4.6
      ],
      "color": "#c78345",
      "collide": false,
      "bevel": 0.035
    },
    {
      "id": "classroom_door_1_window",
      "size": [
        0.035,
        0.72,
        0.44
      ],
      "pos": [
        4.45,
        2.05,
        -4.6
      ],
      "color": "#8ec8d6",
      "collide": false,
      "emissive": "#a9deea"
    },
    {
      "id": "classroom_door_1_handle",
      "size": [
        0.08,
        0.1,
        0.08
      ],
      "pos": [
        4.42,
        1.15,
        -5.02
      ],
      "color": "#f0cf78",
      "collide": false,
      "bevel": 0.02
    },
    {
      "id": "classroom_door_2",
      "size": [
        0.05,
        2.8,
        1.25
      ],
      "pos": [
        4.485,
        1.4,
        0.2
      ],
      "color": "#d69a4b",
      "collide": false,
      "bevel": 0.035
    },
    {
      "id": "classroom_door_2_window",
      "size": [
        0.035,
        0.72,
        0.44
      ],
      "pos": [
        4.45,
        2.05,
        0.2
      ],
      "color": "#8ec8d6",
      "collide": false,
      "emissive": "#a9deea"
    },
    {
      "id": "classroom_door_2_handle",
      "size": [
        0.08,
        0.1,
        0.08
      ],
      "pos": [
        4.42,
        1.15,
        -0.21999999999999997
      ],
      "color": "#f0cf78",
      "collide": false,
      "bevel": 0.02
    },
    {
      "id": "classroom_door_3",
      "size": [
        0.05,
        2.8,
        1.25
      ],
      "pos": [
        4.485,
        1.4,
        5
      ],
      "color": "#c78345",
      "collide": false,
      "bevel": 0.035
    },
    {
      "id": "classroom_door_3_window",
      "size": [
        0.035,
        0.72,
        0.44
      ],
      "pos": [
        4.45,
        2.05,
        5
      ],
      "color": "#8ec8d6",
      "collide": false,
      "emissive": "#a9deea"
    },
    {
      "id": "classroom_door_3_handle",
      "size": [
        0.08,
        0.1,
        0.08
      ],
      "pos": [
        4.42,
        1.15,
        4.58
      ],
      "color": "#f0cf78",
      "collide": false,
      "bevel": 0.02
    },
    {
      "id": "ceiling_light_1",
      "size": [
        1.1,
        0.08,
        0.4
      ],
      "pos": [
        0,
        4.04,
        -6
      ],
      "color": "#ffffff",
      "collide": false,
      "emissive": "#fff7db"
    },
    {
      "id": "ceiling_light_2",
      "size": [
        1.1,
        0.08,
        0.4
      ],
      "pos": [
        0,
        4.04,
        -3
      ],
      "color": "#ffffff",
      "collide": false,
      "emissive": "#fff7db"
    },
    {
      "id": "ceiling_light_3",
      "size": [
        1.1,
        0.08,
        0.4
      ],
      "pos": [
        0,
        4.04,
        0
      ],
      "color": "#ffffff",
      "collide": false,
      "emissive": "#fff7db"
    },
    {
      "id": "ceiling_light_4",
      "size": [
        1.1,
        0.08,
        0.4
      ],
      "pos": [
        0,
        4.04,
        3
      ],
      "color": "#ffffff",
      "collide": false,
      "emissive": "#fff7db"
    },
    {
      "id": "ceiling_light_5",
      "size": [
        1.1,
        0.08,
        0.4
      ],
      "pos": [
        0,
        4.04,
        6
      ],
      "color": "#ffffff",
      "collide": false,
      "emissive": "#fff7db"
    },
    {
      "id": "notice_board",
      "size": [
        0.06,
        1.35,
        2.1
      ],
      "pos": [
        4.48,
        1.8,
        6.25
      ],
      "color": "#ae6f42",
      "collide": false,
      "bevel": 0.025,
      "decor": true
    },
    {
      "id": "notice_card_blue",
      "size": [
        0.03,
        0.44,
        0.55
      ],
      "pos": [
        4.44,
        2.03,
        5.8
      ],
      "color": "#5ba8d1",
      "collide": false,
      "decor": true
    },
    {
      "id": "notice_card_yellow",
      "size": [
        0.03,
        0.38,
        0.48
      ],
      "pos": [
        4.44,
        1.55,
        6.45
      ],
      "color": "#f4cf55",
      "collide": false,
      "decor": true
    },
    {
      "id": "hall_plant_pot",
      "shape": "cylinder",
      "size": [
        0.24,
        0.45,
        0
      ],
      "pos": [
        3.95,
        0.225,
        7.3
      ],
      "color": "#b95f3f",
      "collide": true,
      "decor": true
    },
    {
      "id": "hall_plant",
      "shape": "sphere",
      "size": [
        0.48,
        0,
        0
      ],
      "pos": [
        3.95,
        0.85,
        7.3
      ],
      "color": "#4c9d62",
      "collide": false,
      "decor": true
    }
  ],
  "marks": {
    "hall_center": {
      "pos": [
        0,
        0,
        0
      ],
      "facingDeg": 0
    },
    "lockers": {
      "pos": [
        -3.25,
        0,
        1.2
      ],
      "facingDeg": -90
    },
    "hall_door_inside": {
      "pos": [
        0,
        0,
        -7
      ],
      "facingDeg": 0
    },
    "notice_board": {
      "pos": [
        3.25,
        0,
        6.25
      ],
      "facingDeg": 90
    },
    "water_fountain": {
      "pos": [
        3.25,
        0,
        -2.3
      ],
      "facingDeg": 90
    },
    "hall_end": {
      "pos": [
        0,
        0,
        5.8
      ],
      "facingDeg": 180
    }
  },
  "anchors": {
    "locker_focus": [
      -3.95,
      1.15,
      1.2
    ],
    "trophy_case_focus": [
      4,
      1.4,
      3.7
    ]
  },
  "cameraSafe": {
    "min": [
      -4,
      0.2,
      -7.6
    ],
    "max": [
      4,
      3.95,
      7.6
    ],
    "audienceSideOnly": false
  },
  "composition": {
    "actionSafe": {
      "left": 0.06,
      "right": 0.86,
      "top": 0.1,
      "bottom": 0.8
    },
    "stageLine": {
      "a": [
        -3.2,
        0,
        0
      ],
      "b": [
        3.2,
        0,
        0
      ]
    }
  },
  "lighting": {
    "day": {
      "sunDir": [
        -0.45,
        0.86,
        0.35
      ],
      "sunColor": "#fff4d8",
      "sunIntensity": 1.85,
      "sky": "#c8deea",
      "ground": "#9d8b73",
      "ambientIntensity": 0.72,
      "fog": "#e5edf0",
      "fogNear": 24,
      "fogFar": 58,
      "exposure": 1.02
    },
    "after_school": {
      "sunDir": [
        0.65,
        0.68,
        0.35
      ],
      "sunColor": "#ffd2a1",
      "sunIntensity": 1.55,
      "sky": "#b8cbe0",
      "ground": "#95745c",
      "ambientIntensity": 0.62,
      "fog": "#e7ded7",
      "fogNear": 22,
      "fogFar": 52,
      "exposure": 1.08
    }
  },
  "extras": {
    "decorDensity": 1,
    "backgroundCharacters": 0
  },
  "notes": "Original procedural school corridor with ten authored lockers, classroom doors, trophy case, fountain, notices and a collision-clear 1.40m x 3.05m end doorway.",
  "license": {
    "source": "original-procedural",
    "author": "RBLX SPARK (in-house)",
    "license": "Proprietary - owned",
    "attributionRequired": false,
    "notes": "Original primitive geometry and procedural dressing authored in-house; no Roblox or copied map assets."
  }
} as unknown as EnvironmentManifest;
export const PLAYGROUND_MANIFEST = {
  "kind": "environment",
  "id": "playground",
  "version": "1.0.0",
  "displayName": "Spark School Playground",
  "units": "meters",
  "axes": {
    "up": "+y",
    "stageRight": "+x",
    "towardAudience": "+z"
  },
  "bounds": {
    "min": [
      -8,
      0,
      -7
    ],
    "max": [
      8,
      5,
      8
    ]
  },
  "pieces": [
    {
      "id": "ground",
      "size": [
        16,
        0.1,
        15
      ],
      "pos": [
        0,
        -0.05,
        0.5
      ],
      "color": "#72a85e",
      "collide": true
    },
    {
      "id": "rubber_play_surface",
      "size": [
        9.2,
        0.035,
        7.4
      ],
      "pos": [
        0,
        0.01,
        -0.7
      ],
      "color": "#5d85a8",
      "collide": false,
      "bevel": 0.02
    },
    {
      "id": "path",
      "size": [
        2.2,
        0.025,
        5
      ],
      "pos": [
        0,
        0.018,
        5.5
      ],
      "color": "#d6c8a7",
      "collide": false
    },
    {
      "id": "slide_platform",
      "size": [
        1.4,
        0.18,
        1.4
      ],
      "pos": [
        -3,
        1.8,
        -0.8
      ],
      "color": "#f6c445",
      "collide": true,
      "bevel": 0.04
    },
    {
      "id": "slide_post_1",
      "size": [
        0.18,
        1.8,
        0.18
      ],
      "pos": [
        -3.55,
        0.9,
        -1.35
      ],
      "color": "#e0524d",
      "collide": true,
      "bevel": 0.025
    },
    {
      "id": "slide_post_2",
      "size": [
        0.18,
        1.8,
        0.18
      ],
      "pos": [
        -2.45,
        0.9,
        -1.35
      ],
      "color": "#e0524d",
      "collide": true,
      "bevel": 0.025
    },
    {
      "id": "slide_post_3",
      "size": [
        0.18,
        1.8,
        0.18
      ],
      "pos": [
        -3.55,
        0.9,
        -0.25
      ],
      "color": "#e0524d",
      "collide": true,
      "bevel": 0.025
    },
    {
      "id": "slide_post_4",
      "size": [
        0.18,
        1.8,
        0.18
      ],
      "pos": [
        -2.45,
        0.9,
        -0.25
      ],
      "color": "#e0524d",
      "collide": true,
      "bevel": 0.025
    },
    {
      "id": "slide_chute",
      "size": [
        1.05,
        0.22,
        3.2
      ],
      "pos": [
        -3,
        1.05,
        1.45
      ],
      "color": "#f28c35",
      "collide": false,
      "rotDeg": [
        -24,
        0,
        0
      ],
      "bevel": 0.025
    },
    {
      "id": "slide_rail_left",
      "size": [
        0.09,
        0.22,
        3.25
      ],
      "pos": [
        -3.57,
        1.23,
        1.4
      ],
      "color": "#ffd760",
      "collide": false,
      "rotDeg": [
        -24,
        0,
        0
      ]
    },
    {
      "id": "slide_rail_right",
      "size": [
        0.09,
        0.22,
        3.25
      ],
      "pos": [
        -2.43,
        1.23,
        1.4
      ],
      "color": "#ffd760",
      "collide": false,
      "rotDeg": [
        -24,
        0,
        0
      ]
    },
    {
      "id": "slide_ladder_left",
      "size": [
        0.12,
        1.9,
        0.12
      ],
      "pos": [
        -3.45,
        0.95,
        -1.85
      ],
      "color": "#365d86",
      "collide": true,
      "rotDeg": [
        12,
        0,
        0
      ]
    },
    {
      "id": "slide_ladder_right",
      "size": [
        0.12,
        1.9,
        0.12
      ],
      "pos": [
        -2.55,
        0.95,
        -1.85
      ],
      "color": "#365d86",
      "collide": true,
      "rotDeg": [
        12,
        0,
        0
      ]
    },
    {
      "id": "swing_top_bar",
      "size": [
        3.6,
        0.18,
        0.18
      ],
      "pos": [
        2.5,
        2.9,
        -1.8
      ],
      "color": "#315c7d",
      "collide": true,
      "bevel": 0.03
    },
    {
      "id": "swing_post_left",
      "size": [
        0.2,
        2.9,
        0.2
      ],
      "pos": [
        0.75,
        1.45,
        -1.8
      ],
      "color": "#315c7d",
      "collide": true,
      "bevel": 0.025
    },
    {
      "id": "swing_post_right",
      "size": [
        0.2,
        2.9,
        0.2
      ],
      "pos": [
        4.25,
        1.45,
        -1.8
      ],
      "color": "#315c7d",
      "collide": true,
      "bevel": 0.025
    },
    {
      "id": "swing_rope_1a",
      "size": [
        0.035,
        1.45,
        0.035
      ],
      "pos": [
        1.75,
        2.12,
        -1.8
      ],
      "color": "#e9e0c8",
      "collide": false
    },
    {
      "id": "swing_rope_1b",
      "size": [
        0.035,
        1.45,
        0.035
      ],
      "pos": [
        2.1,
        2.12,
        -1.8
      ],
      "color": "#e9e0c8",
      "collide": false
    },
    {
      "id": "swing_seat_1",
      "size": [
        0.65,
        0.09,
        0.34
      ],
      "pos": [
        1.925,
        1.38,
        -1.8
      ],
      "color": "#e0524d",
      "collide": true,
      "bevel": 0.025
    },
    {
      "id": "swing_rope_2a",
      "size": [
        0.035,
        1.45,
        0.035
      ],
      "pos": [
        2.9,
        2.12,
        -1.8
      ],
      "color": "#e9e0c8",
      "collide": false
    },
    {
      "id": "swing_rope_2b",
      "size": [
        0.035,
        1.45,
        0.035
      ],
      "pos": [
        3.25,
        2.12,
        -1.8
      ],
      "color": "#e9e0c8",
      "collide": false
    },
    {
      "id": "swing_seat_2",
      "size": [
        0.65,
        0.09,
        0.34
      ],
      "pos": [
        3.075,
        1.38,
        -1.8
      ],
      "color": "#f6c445",
      "collide": true,
      "bevel": 0.025
    },
    {
      "id": "sandpit_sand",
      "size": [
        3.5,
        0.08,
        2.7
      ],
      "pos": [
        3,
        0.02,
        3.55
      ],
      "color": "#edcf87",
      "collide": false,
      "bevel": 0.08
    },
    {
      "id": "sandpit_edge_left",
      "size": [
        0.18,
        0.28,
        2.9
      ],
      "pos": [
        1.15,
        0.14,
        3.55
      ],
      "color": "#a86f3f",
      "collide": true,
      "bevel": 0.04
    },
    {
      "id": "sandpit_edge_right",
      "size": [
        0.18,
        0.28,
        2.9
      ],
      "pos": [
        4.85,
        0.14,
        3.55
      ],
      "color": "#a86f3f",
      "collide": true,
      "bevel": 0.04
    },
    {
      "id": "sandpit_edge_back",
      "size": [
        3.9,
        0.28,
        0.18
      ],
      "pos": [
        3,
        0.14,
        4.95
      ],
      "color": "#a86f3f",
      "collide": true,
      "bevel": 0.04
    },
    {
      "id": "sandpit_edge_front",
      "size": [
        3.9,
        0.28,
        0.18
      ],
      "pos": [
        3,
        0.14,
        2.15
      ],
      "color": "#a86f3f",
      "collide": true,
      "bevel": 0.04
    },
    {
      "id": "bench_seat",
      "size": [
        2.1,
        0.16,
        0.55
      ],
      "pos": [
        -4.9,
        0.62,
        4.3
      ],
      "color": "#9a6338",
      "collide": true,
      "bevel": 0.04
    },
    {
      "id": "bench_back",
      "size": [
        2.1,
        0.85,
        0.14
      ],
      "pos": [
        -4.9,
        1.05,
        4.55
      ],
      "color": "#9a6338",
      "collide": true,
      "bevel": 0.03
    },
    {
      "id": "bench_legs",
      "size": [
        1.7,
        0.62,
        0.35
      ],
      "pos": [
        -4.9,
        0.31,
        4.3
      ],
      "color": "#3b5363",
      "collide": true
    },
    {
      "id": "hopscotch_1",
      "size": [
        0.7,
        0.018,
        0.7
      ],
      "pos": [
        -0.35,
        0.02,
        3.15
      ],
      "color": "#ef6f61",
      "collide": false
    },
    {
      "id": "hopscotch_2",
      "size": [
        0.7,
        0.018,
        0.7
      ],
      "pos": [
        0.35,
        0.02,
        3.85
      ],
      "color": "#f5ca55",
      "collide": false
    },
    {
      "id": "hopscotch_3",
      "size": [
        0.7,
        0.018,
        0.7
      ],
      "pos": [
        -0.35,
        0.02,
        4.55
      ],
      "color": "#65b6a5",
      "collide": false
    },
    {
      "id": "fence_back_left",
      "size": [
        6.8,
        1.4,
        0.12
      ],
      "pos": [
        -4.6,
        0.7,
        -6.94
      ],
      "color": "#f2ead7",
      "collide": true
    },
    {
      "id": "fence_back_right",
      "size": [
        6.8,
        1.4,
        0.12
      ],
      "pos": [
        4.6,
        0.7,
        -6.94
      ],
      "color": "#f2ead7",
      "collide": true
    },
    {
      "id": "fence_left",
      "size": [
        0.12,
        1.4,
        15
      ],
      "pos": [
        -7.94,
        0.7,
        0.5
      ],
      "color": "#f2ead7",
      "collide": true
    },
    {
      "id": "fence_right",
      "size": [
        0.12,
        1.4,
        15
      ],
      "pos": [
        7.94,
        0.7,
        0.5
      ],
      "color": "#f2ead7",
      "collide": true
    },
    {
      "id": "slide_ladder_step_1",
      "size": [
        0.88,
        0.08,
        0.16
      ],
      "pos": [
        -3,
        0.35,
        -1.92
      ],
      "color": "#6ea6c7",
      "collide": false,
      "bevel": 0.018
    },
    {
      "id": "slide_ladder_step_2",
      "size": [
        0.88,
        0.08,
        0.16
      ],
      "pos": [
        -3,
        0.62,
        -1.92
      ],
      "color": "#6ea6c7",
      "collide": false,
      "bevel": 0.018
    },
    {
      "id": "slide_ladder_step_3",
      "size": [
        0.88,
        0.08,
        0.16
      ],
      "pos": [
        -3,
        0.89,
        -1.92
      ],
      "color": "#6ea6c7",
      "collide": false,
      "bevel": 0.018
    },
    {
      "id": "slide_ladder_step_4",
      "size": [
        0.88,
        0.08,
        0.16
      ],
      "pos": [
        -3,
        1.1600000000000001,
        -1.92
      ],
      "color": "#6ea6c7",
      "collide": false,
      "bevel": 0.018
    },
    {
      "id": "slide_ladder_step_5",
      "size": [
        0.88,
        0.08,
        0.16
      ],
      "pos": [
        -3,
        1.4300000000000002,
        -1.92
      ],
      "color": "#6ea6c7",
      "collide": false,
      "bevel": 0.018
    },
    {
      "id": "slide_ladder_step_6",
      "size": [
        0.88,
        0.08,
        0.16
      ],
      "pos": [
        -3,
        1.7000000000000002,
        -1.92
      ],
      "color": "#6ea6c7",
      "collide": false,
      "bevel": 0.018
    },
    {
      "id": "tree_trunk_1",
      "shape": "cylinder",
      "size": [
        0.22,
        2.4,
        0
      ],
      "pos": [
        -6.4,
        1.2,
        -4.7
      ],
      "color": "#7a5132",
      "collide": true,
      "decor": true
    },
    {
      "id": "tree_crown_1",
      "shape": "sphere",
      "size": [
        1.15,
        0,
        0
      ],
      "pos": [
        -6.4,
        2.9,
        -4.7
      ],
      "color": "#55a969",
      "collide": false,
      "decor": true
    },
    {
      "id": "tree_crown_1_small",
      "shape": "sphere",
      "size": [
        0.75,
        0,
        0
      ],
      "pos": [
        -5.800000000000001,
        2.65,
        -4.55
      ],
      "color": "#63b674",
      "collide": false,
      "decor": true
    },
    {
      "id": "tree_trunk_2",
      "shape": "cylinder",
      "size": [
        0.22,
        2.4,
        0
      ],
      "pos": [
        6.1,
        1.2,
        -4.9
      ],
      "color": "#7a5132",
      "collide": true,
      "decor": true
    },
    {
      "id": "tree_crown_2",
      "shape": "sphere",
      "size": [
        1.15,
        0,
        0
      ],
      "pos": [
        6.1,
        2.9,
        -4.9
      ],
      "color": "#4b985c",
      "collide": false,
      "decor": true
    },
    {
      "id": "tree_crown_2_small",
      "shape": "sphere",
      "size": [
        0.75,
        0,
        0
      ],
      "pos": [
        6.699999999999999,
        2.65,
        -4.75
      ],
      "color": "#63b674",
      "collide": false,
      "decor": true
    },
    {
      "id": "tree_trunk_3",
      "shape": "cylinder",
      "size": [
        0.22,
        2.4,
        0
      ],
      "pos": [
        -6.2,
        1.2,
        6.1
      ],
      "color": "#7a5132",
      "collide": true,
      "decor": true
    },
    {
      "id": "tree_crown_3",
      "shape": "sphere",
      "size": [
        1.15,
        0,
        0
      ],
      "pos": [
        -6.2,
        2.9,
        6.1
      ],
      "color": "#55a969",
      "collide": false,
      "decor": true
    },
    {
      "id": "tree_crown_3_small",
      "shape": "sphere",
      "size": [
        0.75,
        0,
        0
      ],
      "pos": [
        -5.6000000000000005,
        2.65,
        6.25
      ],
      "color": "#63b674",
      "collide": false,
      "decor": true
    }
  ],
  "marks": {
    "play_center": {
      "pos": [
        0,
        0,
        0.9
      ],
      "facingDeg": 0
    },
    "slide": {
      "pos": [
        -1.6,
        0,
        1.8
      ],
      "facingDeg": -90
    },
    "swings": {
      "pos": [
        2.5,
        0,
        -0.55
      ],
      "facingDeg": 180
    },
    "sandpit": {
      "pos": [
        3,
        0,
        3.55
      ],
      "facingDeg": 180
    },
    "bench": {
      "pos": [
        -3.5,
        0,
        4.3
      ],
      "facingDeg": -90
    },
    "playground_path": {
      "pos": [
        0,
        0,
        5.5
      ],
      "facingDeg": 180
    }
  },
  "anchors": {
    "slide_focus": [
      -3,
      1.1,
      0.5
    ],
    "swing_focus": [
      2.5,
      1.7,
      -1.8
    ],
    "sandpit_center": [
      3,
      0.08,
      3.55
    ]
  },
  "cameraSafe": {
    "min": [
      -7.4,
      0.2,
      -6.4
    ],
    "max": [
      7.4,
      4.5,
      7.4
    ],
    "audienceSideOnly": false
  },
  "composition": {
    "actionSafe": {
      "left": 0.06,
      "right": 0.86,
      "top": 0.1,
      "bottom": 0.8
    },
    "stageLine": {
      "a": [
        -5.5,
        0,
        0.8
      ],
      "b": [
        5.5,
        0,
        0.8
      ]
    }
  },
  "lighting": {
    "day": {
      "sunDir": [
        -0.58,
        0.8,
        0.25
      ],
      "sunColor": "#fff1cf",
      "sunIntensity": 2.2,
      "sky": "#8ecaf0",
      "ground": "#77a765",
      "ambientIntensity": 0.7,
      "fog": "#d9eef7",
      "fogNear": 28,
      "fogFar": 70,
      "exposure": 1
    },
    "sunset": {
      "sunDir": [
        0.75,
        0.5,
        0.3
      ],
      "sunColor": "#ffb36b",
      "sunIntensity": 2,
      "sky": "#8faed1",
      "ground": "#9a694c",
      "ambientIntensity": 0.55,
      "fog": "#e9c5b0",
      "fogNear": 24,
      "fogFar": 62,
      "exposure": 1.08
    }
  },
  "extras": {
    "decorDensity": 1,
    "backgroundCharacters": 0
  },
  "notes": "Original procedural playground with a climbable slide silhouette, two swings, bordered sandpit, bench, hopscotch, trees, fence and unobstructed authored staging marks.",
  "license": {
    "source": "original-procedural",
    "author": "RBLX SPARK (in-house)",
    "license": "Proprietary - owned",
    "attributionRequired": false,
    "notes": "Original primitive geometry and procedural dressing authored in-house; no Roblox or copied map assets."
  }
} as unknown as EnvironmentManifest;
