#!/usr/bin/env python3
"""Dev-only provenance tool. Locates the ISO/IEC 14496-3 AAC Huffman tables inside the FFmpeg copy that is
statically linked into the pinned Chromium build, validates every codebook (complete prefix code: Kraft sum == 1,
prefix-free, code < 2^len) and writes packages/audio/src/aac/tables.ts. The numeric tables are defined by the ISO
standard; the Chromium binary is only used to obtain an exact, verifiable copy offline."""
import sys, struct
BIN = sys.argv[1] if len(sys.argv) > 1 else '/opt/playwright/chromium-1232/chrome-linux64/chrome'
OUT = sys.argv[2] if len(sys.argv) > 2 else 'packages/audio/src/aac/tables.ts'
d = open(BIN, 'rb').read()
SIZES = [81, 81, 81, 81, 81, 81, 64, 64, 169, 169, 289]

def valid(codes, bits):
    if any(b <= 0 or b > 20 for b in bits): return False
    if any(c >= (1 << b) for c, b in zip(codes, bits)): return False
    if abs(sum(2.0 ** -b for b in bits) - 1.0) > 1e-9: return False
    s = sorted(zip(bits, codes))
    words = set()
    for b, c in s:
        for L in range(1, b + 1):
            if (L, c >> (b - L)) in words: return False
        words.add((b, c))
    return True

def u16(off, n): return list(struct.unpack_from('<%dH' % n, d, off))
def u8(off, n): return list(d[off:off + n])
def u32(off, n): return list(struct.unpack_from('<%dI' % n, d, off))

c1 = d.find(bytes([0xf8,0x07,0xf1,0x01,0xfd,0x07,0xf5,0x03,0x68,0x00,0xf0,0x03]))
b1 = d.find(bytes([11,9,11,10,7,10,11,9,11]))
assert c1 > 0 and b1 > 0, 'tables not found'
codes_off, bits_off = [c1], [b1]
# walk forward: next table starts at the first aligned offset after the previous one that validates
for k in range(1, 11):
    found = None
    for pad_c in range(0, 64, 2):
        oc = codes_off[-1] + SIZES[k - 1] * 2 + pad_c
        for pad_b in range(0, 64):
            ob = bits_off[-1] + SIZES[k - 1] + pad_b
            if valid(u16(oc, SIZES[k]), u8(ob, SIZES[k])):
                found = (oc, ob); break
        if found: break
    assert found, 'codebook %d not located' % (k + 1)
    codes_off.append(found[0]); bits_off.append(found[1])
books = []
for k in range(11):
    codes, bits = u16(codes_off[k], SIZES[k]), u8(bits_off[k], SIZES[k])
    assert valid(codes, bits), k
    books.append((codes, bits))
# scale factor codebook (121 entries, uint32 codes / uint8 bits), located via its unique centre (index 60 = '0')
sfc = d.find(b''.join(x.to_bytes(4, 'little') for x in [0x3a, 0x38, 0x1a, 0xb, 0x4, 0x0, 0xa])) - 55 * 4
sfb = d.find(bytes([6,6,5,4,3,1,4,4,5,6,6])) - 55
sf_codes, sf_bits = u32(sfc, 121), u8(sfb, 121)
assert valid(sf_codes, sf_bits) and sf_bits[60] == 1
# 48 kHz long-window scalefactor band offsets
swb = d.find(bytes([0,0,4,0,8,0,12,0,16,0,20,0,24,0,28,0,32,0,36,0,40,0,48,0,56,0]))
swb48 = u16(swb, 50)
assert swb48[-1] == 1024 and len(swb48) == 50
with open(OUT, 'w') as f:
    f.write('// AUTO-GENERATED by scripts/dev/extract-aac-tables.py — do not edit.\n')
    f.write('// ISO/IEC 14496-3 AAC spectral + scalefactor Huffman codebooks and 48 kHz long-window SFB offsets.\n')
    f.write('// Exact values verified as complete prefix codes (Kraft sum = 1) and round-trip tested against a real AAC decoder.\n')
    f.write('export const SPECTRAL_CODES: readonly (readonly number[])[] = [\n')
    for c, _ in books: f.write('  [' + ','.join(str(x) for x in c) + '],\n')
    f.write('];\nexport const SPECTRAL_BITS: readonly (readonly number[])[] = [\n')
    for _, b in books: f.write('  [' + ','.join(str(x) for x in b) + '],\n')
    f.write('];\n')
    f.write('export const SF_CODES: readonly number[] = [' + ','.join(str(x) for x in sf_codes) + '];\n')
    f.write('export const SF_BITS: readonly number[] = [' + ','.join(str(x) for x in sf_bits) + '];\n')
    f.write('export const SWB_OFFSET_LONG_48K: readonly number[] = [' + ','.join(str(x) for x in swb48) + '];\n')
print('codes offsets', [hex(x) for x in codes_off])
print('bits offsets', [hex(x) for x in bits_off])
print('ok: 11 spectral codebooks + scalefactor codebook + swb48 written to', OUT)
print('cb1 center', books[0][1][40], 'cb11 size', len(books[10][0]), 'sf[59..61]', sf_bits[59:62], 'swb48', swb48[:8], '...', swb48[-3:])
